Person: {
    shape: class
    Name: string
    Bank: int
    OfAge: bool
}

Cat: {
    shape: class
    Color: string
    Age: int
    FavoriteSnacks: string
}

FeedCat: {
    shape: class

    GiveSnack(amount int): string
    ScratchOwner(amount int): bool
    
}

Snacks: {
    shape: class

    SnackCabinet: string
}

#STOP

Person -> FeedCat: Wants to
FeedCat -> Cat: Snack goes to
Cat -> FavoriteSnacks: Has
